extensions/urls.py
from django.conf.urls import url
from . import views

# 指定命名空间和前缀，避免和其他url重复
app_name = 'plugins'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'proxy', views.proxy, name='proxy')
]

plugins/bbs/urls.py
from django.http import HttpResponse
from django.urls import path
from . import views

name = 'test'
# 变量必须是urlpatterns，在系统启动的时候 自动进行注册
urlpatterns = [
    path('asd', views.index, name='index'),
    path('hello', views.hello, name='hello'),
]

plugins/mobile/urls.py
from django.http import HttpResponse
from django.urls import path
from . import views

name = 'mobile'
# 变量必须是urlpatterns，在系统启动的时候 自动进行注册
urlpatterns = [
    path('asd', views.index, name='index'),
    path('hello', views.hello, name='hello'),
]

simplepro_demo/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponse
from django.conf.urls.static import static
from django.urls import path

admin.site.site_title = '管理后台PRO'
admin.site.site_header = '员工管理后台PRO'


def test(request):
    return HttpResponse('ok')


urlpatterns = [
                  path('', admin.site.urls),
                  path('test', test),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extensions/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.encoding import force_text
from django.utils.functional import Promise
from django.views.decorators.csrf import csrf_exempt

from extensions.core import loader

import requests

from . import conf
import json


class LazyEncoder(DjangoJSONEncoder):
    """
        解决json __proxy__ 问题
    """

    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.strftime("%Y-%m-%d %H:%M:%S")
        elif isinstance(obj, datetime.date):
            return obj.strftime("%Y-%m-%d")
        elif isinstance(obj, Promise):
            return force_text(obj)
        return str(obj)


# 为了安全，只允许登录的访问

def write(data=None, msg='ok'):
    rs = {
        'state': not data,
        'msg': 'ok',
        'data': data
    }
    return HttpResponse(json.dumps(rs), content_type='application/json')


@login_required
def index(request):
    return render(request, 'plugins/index.html', {
        'apps': loader.DATA.get('apps')
    })


@csrf_exempt
def proxy(request):
    post = json.loads(request.body.decode())
    method = post.get('method')
    url = '{}{}/'.format(conf.get_url(), method)
    r = requests.post(url, data=post)
    if r.status_code == 200:
        return HttpResponse(r.text, content_type='application/json')
    else:
        return write(msg='服务器开了小差，稍后再试！')

plugins/bbs/views.py
from django.http import HttpResponse
import json

from django.shortcuts import render
import datetime


def index(request):
    return render(request, 'hello.html', {
        'date': datetime.datetime.now()
    })


def hello(request):
    return HttpResponse(json.dumps({'a': 'ok'}), content_type='application/json')

plugins/mobile/views.py
from django.http import HttpResponse
import json

from django.shortcuts import render
import datetime


def index(request):
    return render(request, 'hello.html', {
        'date': datetime.datetime.now()
    })


def hello(request):
    return HttpResponse(json.dumps({'a': 'ok'}), content_type='application/json')

extensions/templates/plugins/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>插件中心</title>
    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <link rel="stylesheet" href="{% static 'plugins/css/style.css' %}">
</head>
<body>
<div id="app" v-cloak>
    <el-breadcrumb separator-class="el-icon-arrow-right breadcrumb">
        <el-breadcrumb-item>首页</el-breadcrumb-item>
        <el-breadcrumb-item>插件中心</el-breadcrumb-item>
    </el-breadcrumb>

    <div class="categorys" v-loading="loading">
        <el-button-group>

            <el-button size="small" v-for="item in category" :class="{active:item.active}" @click="selectCategory(item)"
                       v-text="item.name" :key="item.id"></el-button>
        </el-button-group>
    </div>

    <el-card class="box-card">
        <div class="toolbar">
            <el-button type="primary" size="small" circle icon="el-icon-refresh"></el-button>

{#            <el-button-group>#}
{#                <el-button size="small" type="success" icon="el-icon-tickets">全部</el-button>#}
{#                <el-button size="small" type="success" icon="el-icon-shopping-cart-2">免费</el-button>#}
{#                <el-button size="small" type="success" icon="el-icon-coin">付费</el-button>#}
{#            </el-button-group>#}
            <el-button type="danger" size="small" icon="el-icon-user">用户信息</el-button>

            <el-input
                    size="small"
                    placeholder="请输入内容"
                    prefix-icon="el-icon-search"
                    v-model="searchInput"
                    class="search-input"
            ></el-input>
        </div>
        <div class="table">

            <installed v-if="local" :data="_config.installed"></installed>
            <store v-else :table-data="tableData"></store>

        </div>
    </el-card>
</div>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- 引入组件库 -->
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
<script type="text/javascript">
    const _config = {
        installed:{{ apps|safe }},
        baseUrl:'{% url 'plugins:index' %}'
    }
</script>
<script type="text/javascript" src="{% static 'plugins/js/axios.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/installed.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/store.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/plugins.js' %}"></script>
</body>
</html>